version: '3.8'

services:
  # Backend development overrides
  backend:
    environment:
      NODE_ENV: development
      DEBUG: app:*
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  # Frontend development overrides
  frontend:
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:5001/api
      VITE_SOCKET_URL: http://localhost:5001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true